### ISSUE TITLE
Re-arrange levels on world 1 selector screen

### ISSUE THREAD

**Issue by 2awesomestudio** [2awesomestudio/DimensionDriveIssueTracker#377]
Description
Go to level select screen of world 1 and observe how the levels are not arranged from left to right
Rearenge them. 
Reproduction Steps

Build
0.8.22

![image](https://cloud.githubusercontent.com/assets/9165009/25686230/fb78e6e2-306c-11e7-98dc-66da9575063d.png)

**Comment by david-2awesome** [comment]
Fixed

**Comment by hexxellor** [comment]
While it does appear that the visible order of the levels on the screen was fixed in the current sprint, it seems that it caused an issue with the lock images representing if a level is unlocked or not.

For example, if you have any level **_other than_** 1_4 selected (1_0 - 1_3) no lock image is visible on 1_4 even though it's locked as shown here:
![level 1_4 - no lock visible](https://cloud.githubusercontent.com/assets/892633/26338623/3190944e-3f47-11e7-91b7-a46fcd1629da.png)

As you move your selection over to 1_4, the lock appears, but instead of where it should be, like the other levels, it's positioned near 1_0 which happens to be where it was before this change was done. You can see that here:
![level 1_4 - lock visible near 1_0](https://cloud.githubusercontent.com/assets/892633/26338663/6b1f7072-3f47-11e7-87f4-558372833224.png)

**Comment by david-2awesome** [comment]
Fixed

**Comment by hexxellor** [comment]
Confirmed Fixed In 0.8.1.5
