### ISSUE TITLE
Incorrect input in menus

### ISSUE THREAD

**Issue by david-2awesome** [2awesomestudio/DimensionDriveIssueTracker#380]
### Description

Menus display at the bottom the input that can be used to accept or cancel or other actions. For example button "A" to advance. However, other inputs also work when they shouldn't. Like button X and RT...

### Reproduction Steps
1. Open the menu of the game
2. Press RT in the game pad.
3. The game will advance when it shouldn't.
4. Some combinations of keys that work in menus and SHALL NOT work are:

- [ ]  Button X and RT to advance in menus.
- [ ]  Keyboard key Z and X to advance in menus.
- [ ]  Select to go back in menus.
- [ ]  Backspace to go back in menus.
- [ ]  Button X and RT to advance in dialogues inside levels.
- [ ]  Keyboard key Z and X to advance in dialogues inside levels.
- [ ]  Keyboard key X to accept in pause menu.
- [ ]  Button X and RT to advance in cutscenes.
- [ ] Keyboard key Z and X to advance in cutscenes.

### Build

_**0.8.1.3**_

### Screenshot
No screenshot needed.

**Comment by alejandro-2awesome** [comment]
@david-2awesome can you clarify what is the correct behaviour with keys? you mention X a lot and that is equal jump key = A button on the controller....

**Comment by david-2awesome** [comment]
@alejandro-2awesome The correct behaviour with keys (and gamepad for that matter) is what we show in the UI at the bottom of the HUD. With keyboard we show ENTER to select/accept things and ESC to cancel/go back. Therefore, other keyboard keys like Backspace, Z, X... shall be deactivated. The only inputs allowed for menus should be the ones we show in the UI to be consistent. The list above shows all the places where I could find keys and buttons that work in the current build when they should not work.

**Comment by hexxellor** [comment]
@david-2awesome I verified that the exact issue(s) you mention above are fixed in the latest build, however, there are some other screens that don't follow your comment about the keys on the HUD matching what the user can press on the keyboard or controller. For example, if you are using the keyboard on the menus then the "Delete" button doesn't change to keyboard input, it stays on controller input as shown here:
![delete input button unchanged](https://user-images.githubusercontent.com/892633/29270594-350fecfc-80bd-11e7-8533-2ab6fff06617.png)

Do you want me to add keyboard/controller issues to this tracker issue or add new ones as I find them?

**Comment by alejandro-2awesome** [comment]
Should be fixed now after NX improvements (and input selection behaviors)
