### ISSUE TITLE
Weapon Power Meter Increase Upon Shield Loss, etc.

### ISSUE THREAD

**Issue by hexxellor** [2awesomestudio/DimensionDriveIssueTracker#397]
### Description

When your ship is damaged (for example you're hit by a bullet or run in to an enemy) the power meter for your weapon at the top of the screen increases slightly.

Without knowing the design goal, I'm just wondering if this is intended behavior or not?

### Build
Game Version - Build 0.8.1.41
OS - All

**Comment by david-2awesome** [comment]
Are you sure this happens when hit by a bullet? What may be happening when you get hit by an enemy is that the enemy explodes and it drops an energy drop then your bar raises. But as everything happens so fast it may not be seen. 

Can you clarify what's the issue? You get hit and there is a full reload of energy ?

**Comment by hexxellor** [comment]
I agree. I think something else was happening. Closing this.
